version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE='mydatabase'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD=''
      - MYSQL_ROOT_PASSWORD='some_password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
      # Where our data will be persisted
    volumes:
      - /tmp/xdb_db/mysqld:/var/run/mysqld
      - production-xdb-db:/var/lib/mysql
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379


  web:
    image: haynesb/xdb:${TAG}
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8080 xdb_price_chat.asgi:application"
    ports:
      - 8080:8080
    volumes:
      - /tmp/xdb_db/mysqld:/run/mysqld
    env_file:
      - ../env/prod.env
    depends_on:
      - db
    
  
  django-q:
    image: haynesb/xdb:${TAG}
    command: python manage.py qcluster --settings xdb_price_chat.settings.production
    env_file:
      - ../env/prod.env
    depends_on:
      - web

volumes:
  production-xdb-db:
