version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE='mydatabase'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='some_password'
      - MYSQL_ROOT_PASSWORD='some_password'
      - MYSQL_HOST=''
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
      # Where our data will be persisted
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - production-db:/var/lib/mysql
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379


  web:
    image: haynesb/xdb:${TAG}
    command: >
      sh -c "python manage.py migrate &&
             daphne xdb_price_chat.asgi:application"
    ports:
      - 8000:8000
    volumes:
      - /tmp/app/mysqld:/run/mysqld 
    env_file:
      - ../env/prod.env
    depends_on:
      - db
    
  
  django-q:
    image: haynesb/xdb:${TAG}
    command: python manage.py qcluster
    depends_on:
      - web

volumes:
  production-db:
