# Generated by Django 4.0.4 on 2022-05-20 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xdb', '0002_post_telegram_user_delete_person_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='winning_amount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='winning_transaction',
        ),
        migrations.CreateModel(
            name='Win',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('win_type', models.CharField(max_length=30)),
                ('winning_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('winning_transaction', models.TextField(blank=True, default='', max_length=300)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xdb.post')),
            ],
        ),
    ]
