# Generated by Django 4.0.4 on 2022-05-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xdb', '0003_remove_post_winning_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram_user',
            name='last_name',
        ),
    ]
