# Generated by Django 4.0.4 on 2022-05-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xdb', '0004_remove_telegram_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='twitter_username',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
