# Generated by Django 4.0.4 on 2022-05-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xdb', '0006_post_tweet_hashtags_post_tweet_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tweet_char_length',
            field=models.IntegerField(default=0),
        ),
    ]
