# Generated by Django 4.0.4 on 2022-06-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xdb', '0007_post_tweet_char_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram_user',
            name='wallet_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
